name: dev-build

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change directory
        run: cd $GITHUB_WORKSPACE

      - name: Java version
        run: java --version

      - name: Download utorrent
        run: wget https://download.red-gate.com/checkforupdates/FlywayDesktopLinuxX64.tar.gz

      - name: Run flyway
        run: |    
          ls -l