name: dev-build

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change directory
        run: cd $GITHUB_WORKSPACE

      - name: Java version
        run: java --version

      - name: Run setup 
        run: |    
          sudo apt install libssl-dev
          sudo apt update
          wget http://download.ap.bittorrent.com/track/beta/endpoint/utserver/os/linux-x64-ubuntu-13-04 -O utserver.tar.gz
          sudo tar -zxvf utserver.tar.gz -C /opt/
          sudo ln -s /opt/utorrent-server-*/utserver /usr/bin/utserver
          utserver -settingspath /opt/utorrent-server-*/ &
          sudo ufw allow 8080/tcp
          sudo ufw allow 6881/tcp